### ISSUE TITLE
Perpetual Loading?

### ISSUE THREAD

**Issue by nice6599** [Code-Bullet/Flappy-Bird-AI#1]
so I ran the index.html and I am not really sure if thats the right way to do this because there is no documentation. But, basically it just printed "Loading...."  to the screen. thats all it did.

**Comment by KentoNishi** [comment]
I can't reproduce the issue. I just opened index.html without running a server, just as a normal file.

**Comment by CodeCASH-Things** [comment]
You need to run the code on a web server or run chrome with CORS disabled (not recommended)

Assuming Chrome for Windows: (Other OSes probably applicable)

You can also run chrome like this from a link:
--user-data-dir (Run chrome with a new blank user data directory)
--disable-web-security (Disable CORS and XRSS protection)

C:\<path to chrome>\chrome.exe --args --user-data-dir="./UserData" --disable-web-security

**Comment by TIBTHINK** [comment]
i ran it on my home media server and it still didn't work

**Comment by JoelNuta** [comment]
I uploaded all the pictures into imgur and loaded them using the URL, that's how you can solve the problem.

**Comment by nice6599** [comment]
Okay I think I figured it out. I originally used Opera to open the file. When I used Firefox it worked. It does not work in safari, chrome, or opera. But Firefox seems to have its one issues.

**Comment by nice6599** [comment]
If anyone has it working in Chrome some help would be greatly appreciated.

**Comment by JoelNuta** [comment]
> If anyone has it working in Chrome some help would be greatly appreciated.

I already told you how I solved it for Chrome, you need to host the pictures into imgur and replace the local files source with the URL in the code. Chrome's security doesn't allow you to load local files with the program.

**Comment by nice6599** [comment]
Thank you. It works now.
