### ISSUE TITLE
Ai Gets it easy

### ISSUE THREAD

**Issue by colemanshropshire** [Code-Bullet/Flappy-Bird-AI#10]
By Having the distance between the pipes set to a constant, the ai only needs to know either the top or bottom distance, by making it randomly change by a small amount, the ai would probably struggle more

**Comment by Osrepnay** [comment]
In the original game, the distance between the pipes seems to be constant too, so I think Code Bullet wanted to stay close to the original game

**Comment by colemanshropshire** [comment]
I did some research, and it turns out your right.  guess I should look into this stuff before raising an issue.
