### ISSUE TITLE
Ummm Something is very wrong with the pipes.... 

### ISSUE THREAD

**Issue by jf0772256** [Code-Bullet/Flappy-Bird-AI#2]
When the ai/human player starts -- about 50 unmatched pairs of pipes populate and sometimes pipes that touch and there is no gap... I tried to loos and see what was causing the pipes to be spawned... and see if i could stop it... or try to figure it out... short end of the story - Its not really usable... 

Windows 10 Edu. x64
WAMP server
and a fresh clone of your repo...  (i thought i had a bad clone so i have cloned it twice to just rule it out...)

**Comment by nice6599** [comment]
Do you have a screenshot? I have an issue with the pipes too. I am unsure if it is the same issue as yours.

**Comment by Quillbert** [comment]
i have the same issue

**Comment by nice6599** [comment]
so the solution is to make the changes described in #4

**Comment by jf0772256** [comment]
@nice6599 Works even with christmas thing! Thanks man!
